name: Build on Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install npm
        uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium chromium-headless-shell

      - name: Run end-to-end tests
        run: npm run test:e2e
